name: Deploy to GitHub Pages

on:
  workflow_call:

jobs:
  build:
    name: Build ${{github.event.repository.name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
        run: pnpm run build:prod && cp -r dist/worktimer/browser github-pages

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: ${{  github.event_name  != 'pull_request' }}

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
